/* @flow */

export const GET_USER_MEMBERSHIPS = 'GET_USER_MEMBERSHIPS'
export const GET_USER_PURCHASES = 'GET_USER_PURCHASES'
export const GET_USER_ACCOUNT_BALANCES = 'GET_USER_ACCOUNT_BALANCES'
export const PUT_MANAGE_PROFILE = 'PUT_MANAGE_PROFILE'
export const GET_MANAGE_PROFILE_PREFERENCES_FIELDS = 'GET_MANAGE_PROFILE_PREFERENCES_FIELDS'
export const GET_CLIENT_PREFERNCES = 'GET_CLIENT_PREFERNCES'
export const PREFERENCES_REQUEST = 'PREFERENCES_REQUEST'
export const PREFERENCES_IDS_FILTER = ['1', '21', '22', '23', '24', '25']
export const CREDITCARD_GET_REQUEST = 'CREDITCARD_GET_REQUEST'
export const CREDITCARD_SAVE = 'CREDITCARD_SAVE'
