/* @flow */

const BOOK_MEMBER_CLASSES = 'BOOK_MEMBER_CLASSES'
const BOOK_TRAINER = 'BOOK_TRAINER'
const BOOK_CLINIC = 'BOOK_CLINIC'
const BOOK_SWEAT_CLASSES = 'BOOK_SWEAT_CLASSES'
const VIEW_SCHEDULE = 'VIEW_SCHEDULE'
const PURCHASE_SWEAT_PACKS = 'PURCHASE_SWEAT_PACKS'

const SWEAT_MEMBER = [
    BOOK_SWEAT_CLASSES,
    PURCHASE_SWEAT_PACKS,
    VIEW_SCHEDULE,
]

const BXR_MEMBER = [
    BOOK_MEMBER_CLASSES,
    BOOK_TRAINER,
    BOOK_CLINIC,
    BOOK_SWEAT_CLASSES,
    PURCHASE_SWEAT_PACKS,
    VIEW_SCHEDULE,
]

export default {
    NON_MEMBER: SWEAT_MEMBER,
    SWEAT_MEMBER,
    BXR_MEMBER,
}
